/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QueroSaberMaisRouteImport } from './routes/quero-saber-mais'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedClienteRouteRouteImport } from './routes/_authenticated/cliente/route'
import { Route as AuthenticatedAdminAtendimentoRouteImport } from './routes/_authenticated/admin/atendimento'
import { Route as AuthenticatedAdminAutomacoesLeadsRouteImport } from './routes/_authenticated/admin/automacoes-leads'
import { Route as AuthenticatedAdminCalendarioRouteImport } from './routes/_authenticated/admin/calendario'
import { Route as AuthenticatedAdminConfigMetaRouteImport } from './routes/_authenticated/admin/config-meta'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminDashboardClientesRouteImport } from './routes/_authenticated/admin/dashboard-clientes'
import { Route as AuthenticatedAdminDiagnosticosRouteImport } from './routes/_authenticated/admin/diagnosticos'
import { Route as AuthenticatedAdminEstrategiaRouteImport } from './routes/_authenticated/admin/estrategia'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminMetaAdsRouteImport } from './routes/_authenticated/admin/meta-ads'
import { Route as AuthenticatedAdminPipelineComercialRouteImport } from './routes/_authenticated/admin/pipeline-comercial'
import { Route as AuthenticatedAdminRoiRouteImport } from './routes/_authenticated/admin/roi'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedClienteAtendimentoRouteImport } from './routes/_authenticated/cliente/atendimento'
import { Route as AuthenticatedClienteCalendarioRouteImport } from './routes/_authenticated/cliente/calendario'
import { Route as AuthenticatedClienteClientesRouteImport } from './routes/_authenticated/cliente/clientes'
import { Route as AuthenticatedClienteConexoesRouteImport } from './routes/_authenticated/cliente/conexoes'
import { Route as AuthenticatedClienteConteudoRouteImport } from './routes/_authenticated/cliente/conteudo'
import { Route as AuthenticatedClienteDashboardRouteImport } from './routes/_authenticated/cliente/dashboard'
import { Route as AuthenticatedClienteDiagnosticoRouteImport } from './routes/_authenticated/cliente/diagnostico'
import { Route as AuthenticatedClienteEntregasRouteImport } from './routes/_authenticated/cliente/entregas'
import { Route as AuthenticatedClienteLeadsRouteImport } from './routes/_authenticated/cliente/leads'
import { Route as AuthenticatedClienteMetaAdsRouteImport } from './routes/_authenticated/cliente/meta-ads'
import { Route as AuthenticatedClienteRoiRouteImport } from './routes/_authenticated/cliente/roi'
import { Route as AuthenticatedAdminClientesIndexRouteImport } from './routes/_authenticated/admin/clientes/index'
import { Route as AuthenticatedAdminClientesIdRouteImport } from './routes/_authenticated/admin/clientes/$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QueroSaberMaisRoute = QueroSaberMaisRouteImport.update({
  id: '/quero-saber-mais',
  path: '/quero-saber-mais',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedClienteRouteRoute =
  AuthenticatedClienteRouteRouteImport.update({
    id: '/cliente',
    path: '/cliente',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAtendimentoRoute =
  AuthenticatedAdminAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAutomacoesLeadsRoute =
  AuthenticatedAdminAutomacoesLeadsRouteImport.update({
    id: '/automacoes-leads',
    path: '/automacoes-leads',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminCalendarioRoute =
  AuthenticatedAdminCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminConfigMetaRoute =
  AuthenticatedAdminConfigMetaRouteImport.update({
    id: '/config-meta',
    path: '/config-meta',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDashboardClientesRoute =
  AuthenticatedAdminDashboardClientesRouteImport.update({
    id: '/dashboard-clientes',
    path: '/dashboard-clientes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminDiagnosticosRoute =
  AuthenticatedAdminDiagnosticosRouteImport.update({
    id: '/diagnosticos',
    path: '/diagnosticos',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminEstrategiaRoute =
  AuthenticatedAdminEstrategiaRouteImport.update({
    id: '/estrategia',
    path: '/estrategia',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminMetaAdsRoute =
  AuthenticatedAdminMetaAdsRouteImport.update({
    id: '/meta-ads',
    path: '/meta-ads',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminPipelineComercialRoute =
  AuthenticatedAdminPipelineComercialRouteImport.update({
    id: '/pipeline-comercial',
    path: '/pipeline-comercial',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminRoiRoute = AuthenticatedAdminRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedClienteAtendimentoRoute =
  AuthenticatedClienteAtendimentoRouteImport.update({
    id: '/atendimento',
    path: '/atendimento',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteCalendarioRoute =
  AuthenticatedClienteCalendarioRouteImport.update({
    id: '/calendario',
    path: '/calendario',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteClientesRoute =
  AuthenticatedClienteClientesRouteImport.update({
    id: '/clientes',
    path: '/clientes',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteConexoesRoute =
  AuthenticatedClienteConexoesRouteImport.update({
    id: '/conexoes',
    path: '/conexoes',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteConteudoRoute =
  AuthenticatedClienteConteudoRouteImport.update({
    id: '/conteudo',
    path: '/conteudo',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteDashboardRoute =
  AuthenticatedClienteDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteDiagnosticoRoute =
  AuthenticatedClienteDiagnosticoRouteImport.update({
    id: '/diagnostico',
    path: '/diagnostico',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteEntregasRoute =
  AuthenticatedClienteEntregasRouteImport.update({
    id: '/entregas',
    path: '/entregas',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteLeadsRoute =
  AuthenticatedClienteLeadsRouteImport.update({
    id: '/leads',
    path: '/leads',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteMetaAdsRoute =
  AuthenticatedClienteMetaAdsRouteImport.update({
    id: '/meta-ads',
    path: '/meta-ads',
    getParentRoute: () => AuthenticatedClienteRouteRoute,
  } as any)
const AuthenticatedClienteRoiRoute = AuthenticatedClienteRoiRouteImport.update({
  id: '/roi',
  path: '/roi',
  getParentRoute: () => AuthenticatedClienteRouteRoute,
} as any)
const AuthenticatedAdminClientesIndexRoute =
  AuthenticatedAdminClientesIndexRouteImport.update({
    id: '/clientes/',
    path: '/clientes/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminClientesIdRoute =
  AuthenticatedAdminClientesIdRouteImport.update({
    id: '/clientes/$id',
    path: '/clientes/$id',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/quero-saber-mais': typeof QueroSaberMaisRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRouteRouteWithChildren
  '/admin/atendimento': typeof AuthenticatedAdminAtendimentoRoute
  '/admin/automacoes-leads': typeof AuthenticatedAdminAutomacoesLeadsRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/config-meta': typeof AuthenticatedAdminConfigMetaRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dashboard-clientes': typeof AuthenticatedAdminDashboardClientesRoute
  '/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/admin/estrategia': typeof AuthenticatedAdminEstrategiaRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/meta-ads': typeof AuthenticatedAdminMetaAdsRoute
  '/admin/pipeline-comercial': typeof AuthenticatedAdminPipelineComercialRoute
  '/admin/roi': typeof AuthenticatedAdminRoiRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/cliente/atendimento': typeof AuthenticatedClienteAtendimentoRoute
  '/cliente/calendario': typeof AuthenticatedClienteCalendarioRoute
  '/cliente/clientes': typeof AuthenticatedClienteClientesRoute
  '/cliente/conexoes': typeof AuthenticatedClienteConexoesRoute
  '/cliente/conteudo': typeof AuthenticatedClienteConteudoRoute
  '/cliente/dashboard': typeof AuthenticatedClienteDashboardRoute
  '/cliente/diagnostico': typeof AuthenticatedClienteDiagnosticoRoute
  '/cliente/entregas': typeof AuthenticatedClienteEntregasRoute
  '/cliente/leads': typeof AuthenticatedClienteLeadsRoute
  '/cliente/meta-ads': typeof AuthenticatedClienteMetaAdsRoute
  '/cliente/roi': typeof AuthenticatedClienteRoiRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/quero-saber-mais': typeof QueroSaberMaisRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/cliente': typeof AuthenticatedClienteRouteRouteWithChildren
  '/admin/atendimento': typeof AuthenticatedAdminAtendimentoRoute
  '/admin/automacoes-leads': typeof AuthenticatedAdminAutomacoesLeadsRoute
  '/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/admin/config-meta': typeof AuthenticatedAdminConfigMetaRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/dashboard-clientes': typeof AuthenticatedAdminDashboardClientesRoute
  '/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/admin/estrategia': typeof AuthenticatedAdminEstrategiaRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/meta-ads': typeof AuthenticatedAdminMetaAdsRoute
  '/admin/pipeline-comercial': typeof AuthenticatedAdminPipelineComercialRoute
  '/admin/roi': typeof AuthenticatedAdminRoiRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/cliente/atendimento': typeof AuthenticatedClienteAtendimentoRoute
  '/cliente/calendario': typeof AuthenticatedClienteCalendarioRoute
  '/cliente/clientes': typeof AuthenticatedClienteClientesRoute
  '/cliente/conexoes': typeof AuthenticatedClienteConexoesRoute
  '/cliente/conteudo': typeof AuthenticatedClienteConteudoRoute
  '/cliente/dashboard': typeof AuthenticatedClienteDashboardRoute
  '/cliente/diagnostico': typeof AuthenticatedClienteDiagnosticoRoute
  '/cliente/entregas': typeof AuthenticatedClienteEntregasRoute
  '/cliente/leads': typeof AuthenticatedClienteLeadsRoute
  '/cliente/meta-ads': typeof AuthenticatedClienteMetaAdsRoute
  '/cliente/roi': typeof AuthenticatedClienteRoiRoute
  '/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/admin/clientes': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/quero-saber-mais': typeof QueroSaberMaisRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/cliente': typeof AuthenticatedClienteRouteRouteWithChildren
  '/_authenticated/admin/atendimento': typeof AuthenticatedAdminAtendimentoRoute
  '/_authenticated/admin/automacoes-leads': typeof AuthenticatedAdminAutomacoesLeadsRoute
  '/_authenticated/admin/calendario': typeof AuthenticatedAdminCalendarioRoute
  '/_authenticated/admin/config-meta': typeof AuthenticatedAdminConfigMetaRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/dashboard-clientes': typeof AuthenticatedAdminDashboardClientesRoute
  '/_authenticated/admin/diagnosticos': typeof AuthenticatedAdminDiagnosticosRoute
  '/_authenticated/admin/estrategia': typeof AuthenticatedAdminEstrategiaRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/meta-ads': typeof AuthenticatedAdminMetaAdsRoute
  '/_authenticated/admin/pipeline-comercial': typeof AuthenticatedAdminPipelineComercialRoute
  '/_authenticated/admin/roi': typeof AuthenticatedAdminRoiRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/cliente/atendimento': typeof AuthenticatedClienteAtendimentoRoute
  '/_authenticated/cliente/calendario': typeof AuthenticatedClienteCalendarioRoute
  '/_authenticated/cliente/clientes': typeof AuthenticatedClienteClientesRoute
  '/_authenticated/cliente/conexoes': typeof AuthenticatedClienteConexoesRoute
  '/_authenticated/cliente/conteudo': typeof AuthenticatedClienteConteudoRoute
  '/_authenticated/cliente/dashboard': typeof AuthenticatedClienteDashboardRoute
  '/_authenticated/cliente/diagnostico': typeof AuthenticatedClienteDiagnosticoRoute
  '/_authenticated/cliente/entregas': typeof AuthenticatedClienteEntregasRoute
  '/_authenticated/cliente/leads': typeof AuthenticatedClienteLeadsRoute
  '/_authenticated/cliente/meta-ads': typeof AuthenticatedClienteMetaAdsRoute
  '/_authenticated/cliente/roi': typeof AuthenticatedClienteRoiRoute
  '/_authenticated/admin/clientes/$id': typeof AuthenticatedAdminClientesIdRoute
  '/_authenticated/admin/clientes/': typeof AuthenticatedAdminClientesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/quero-saber-mais'
    | '/admin'
    | '/cliente'
    | '/admin/atendimento'
    | '/admin/automacoes-leads'
    | '/admin/calendario'
    | '/admin/config-meta'
    | '/admin/dashboard'
    | '/admin/dashboard-clientes'
    | '/admin/diagnosticos'
    | '/admin/estrategia'
    | '/admin/leads'
    | '/admin/meta-ads'
    | '/admin/pipeline-comercial'
    | '/admin/roi'
    | '/admin/usuarios'
    | '/cliente/atendimento'
    | '/cliente/calendario'
    | '/cliente/clientes'
    | '/cliente/conexoes'
    | '/cliente/conteudo'
    | '/cliente/dashboard'
    | '/cliente/diagnostico'
    | '/cliente/entregas'
    | '/cliente/leads'
    | '/cliente/meta-ads'
    | '/cliente/roi'
    | '/admin/clientes/$id'
    | '/admin/clientes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/quero-saber-mais'
    | '/admin'
    | '/cliente'
    | '/admin/atendimento'
    | '/admin/automacoes-leads'
    | '/admin/calendario'
    | '/admin/config-meta'
    | '/admin/dashboard'
    | '/admin/dashboard-clientes'
    | '/admin/diagnosticos'
    | '/admin/estrategia'
    | '/admin/leads'
    | '/admin/meta-ads'
    | '/admin/pipeline-comercial'
    | '/admin/roi'
    | '/admin/usuarios'
    | '/cliente/atendimento'
    | '/cliente/calendario'
    | '/cliente/clientes'
    | '/cliente/conexoes'
    | '/cliente/conteudo'
    | '/cliente/dashboard'
    | '/cliente/diagnostico'
    | '/cliente/entregas'
    | '/cliente/leads'
    | '/cliente/meta-ads'
    | '/cliente/roi'
    | '/admin/clientes/$id'
    | '/admin/clientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/quero-saber-mais'
    | '/_authenticated/admin'
    | '/_authenticated/cliente'
    | '/_authenticated/admin/atendimento'
    | '/_authenticated/admin/automacoes-leads'
    | '/_authenticated/admin/calendario'
    | '/_authenticated/admin/config-meta'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/dashboard-clientes'
    | '/_authenticated/admin/diagnosticos'
    | '/_authenticated/admin/estrategia'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/meta-ads'
    | '/_authenticated/admin/pipeline-comercial'
    | '/_authenticated/admin/roi'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/cliente/atendimento'
    | '/_authenticated/cliente/calendario'
    | '/_authenticated/cliente/clientes'
    | '/_authenticated/cliente/conexoes'
    | '/_authenticated/cliente/conteudo'
    | '/_authenticated/cliente/dashboard'
    | '/_authenticated/cliente/diagnostico'
    | '/_authenticated/cliente/entregas'
    | '/_authenticated/cliente/leads'
    | '/_authenticated/cliente/meta-ads'
    | '/_authenticated/cliente/roi'
    | '/_authenticated/admin/clientes/$id'
    | '/_authenticated/admin/clientes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  QueroSaberMaisRoute: typeof QueroSaberMaisRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quero-saber-mais': {
      id: '/quero-saber-mais'
      path: '/quero-saber-mais'
      fullPath: '/quero-saber-mais'
      preLoaderRoute: typeof QueroSaberMaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/cliente': {
      id: '/_authenticated/cliente'
      path: '/cliente'
      fullPath: '/cliente'
      preLoaderRoute: typeof AuthenticatedClienteRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/atendimento': {
      id: '/_authenticated/admin/atendimento'
      path: '/atendimento'
      fullPath: '/admin/atendimento'
      preLoaderRoute: typeof AuthenticatedAdminAtendimentoRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/automacoes-leads': {
      id: '/_authenticated/admin/automacoes-leads'
      path: '/automacoes-leads'
      fullPath: '/admin/automacoes-leads'
      preLoaderRoute: typeof AuthenticatedAdminAutomacoesLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/calendario': {
      id: '/_authenticated/admin/calendario'
      path: '/calendario'
      fullPath: '/admin/calendario'
      preLoaderRoute: typeof AuthenticatedAdminCalendarioRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/config-meta': {
      id: '/_authenticated/admin/config-meta'
      path: '/config-meta'
      fullPath: '/admin/config-meta'
      preLoaderRoute: typeof AuthenticatedAdminConfigMetaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/dashboard-clientes': {
      id: '/_authenticated/admin/dashboard-clientes'
      path: '/dashboard-clientes'
      fullPath: '/admin/dashboard-clientes'
      preLoaderRoute: typeof AuthenticatedAdminDashboardClientesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/diagnosticos': {
      id: '/_authenticated/admin/diagnosticos'
      path: '/diagnosticos'
      fullPath: '/admin/diagnosticos'
      preLoaderRoute: typeof AuthenticatedAdminDiagnosticosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/estrategia': {
      id: '/_authenticated/admin/estrategia'
      path: '/estrategia'
      fullPath: '/admin/estrategia'
      preLoaderRoute: typeof AuthenticatedAdminEstrategiaRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/meta-ads': {
      id: '/_authenticated/admin/meta-ads'
      path: '/meta-ads'
      fullPath: '/admin/meta-ads'
      preLoaderRoute: typeof AuthenticatedAdminMetaAdsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/pipeline-comercial': {
      id: '/_authenticated/admin/pipeline-comercial'
      path: '/pipeline-comercial'
      fullPath: '/admin/pipeline-comercial'
      preLoaderRoute: typeof AuthenticatedAdminPipelineComercialRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/roi': {
      id: '/_authenticated/admin/roi'
      path: '/roi'
      fullPath: '/admin/roi'
      preLoaderRoute: typeof AuthenticatedAdminRoiRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/cliente/atendimento': {
      id: '/_authenticated/cliente/atendimento'
      path: '/atendimento'
      fullPath: '/cliente/atendimento'
      preLoaderRoute: typeof AuthenticatedClienteAtendimentoRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/calendario': {
      id: '/_authenticated/cliente/calendario'
      path: '/calendario'
      fullPath: '/cliente/calendario'
      preLoaderRoute: typeof AuthenticatedClienteCalendarioRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/clientes': {
      id: '/_authenticated/cliente/clientes'
      path: '/clientes'
      fullPath: '/cliente/clientes'
      preLoaderRoute: typeof AuthenticatedClienteClientesRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/conexoes': {
      id: '/_authenticated/cliente/conexoes'
      path: '/conexoes'
      fullPath: '/cliente/conexoes'
      preLoaderRoute: typeof AuthenticatedClienteConexoesRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/conteudo': {
      id: '/_authenticated/cliente/conteudo'
      path: '/conteudo'
      fullPath: '/cliente/conteudo'
      preLoaderRoute: typeof AuthenticatedClienteConteudoRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/dashboard': {
      id: '/_authenticated/cliente/dashboard'
      path: '/dashboard'
      fullPath: '/cliente/dashboard'
      preLoaderRoute: typeof AuthenticatedClienteDashboardRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/diagnostico': {
      id: '/_authenticated/cliente/diagnostico'
      path: '/diagnostico'
      fullPath: '/cliente/diagnostico'
      preLoaderRoute: typeof AuthenticatedClienteDiagnosticoRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/entregas': {
      id: '/_authenticated/cliente/entregas'
      path: '/entregas'
      fullPath: '/cliente/entregas'
      preLoaderRoute: typeof AuthenticatedClienteEntregasRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/leads': {
      id: '/_authenticated/cliente/leads'
      path: '/leads'
      fullPath: '/cliente/leads'
      preLoaderRoute: typeof AuthenticatedClienteLeadsRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/meta-ads': {
      id: '/_authenticated/cliente/meta-ads'
      path: '/meta-ads'
      fullPath: '/cliente/meta-ads'
      preLoaderRoute: typeof AuthenticatedClienteMetaAdsRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/cliente/roi': {
      id: '/_authenticated/cliente/roi'
      path: '/roi'
      fullPath: '/cliente/roi'
      preLoaderRoute: typeof AuthenticatedClienteRoiRouteImport
      parentRoute: typeof AuthenticatedClienteRouteRoute
    }
    '/_authenticated/admin/clientes/': {
      id: '/_authenticated/admin/clientes/'
      path: '/clientes'
      fullPath: '/admin/clientes/'
      preLoaderRoute: typeof AuthenticatedAdminClientesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/clientes/$id': {
      id: '/_authenticated/admin/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/admin/clientes/$id'
      preLoaderRoute: typeof AuthenticatedAdminClientesIdRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAtendimentoRoute: typeof AuthenticatedAdminAtendimentoRoute
  AuthenticatedAdminAutomacoesLeadsRoute: typeof AuthenticatedAdminAutomacoesLeadsRoute
  AuthenticatedAdminCalendarioRoute: typeof AuthenticatedAdminCalendarioRoute
  AuthenticatedAdminConfigMetaRoute: typeof AuthenticatedAdminConfigMetaRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDashboardClientesRoute: typeof AuthenticatedAdminDashboardClientesRoute
  AuthenticatedAdminDiagnosticosRoute: typeof AuthenticatedAdminDiagnosticosRoute
  AuthenticatedAdminEstrategiaRoute: typeof AuthenticatedAdminEstrategiaRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminMetaAdsRoute: typeof AuthenticatedAdminMetaAdsRoute
  AuthenticatedAdminPipelineComercialRoute: typeof AuthenticatedAdminPipelineComercialRoute
  AuthenticatedAdminRoiRoute: typeof AuthenticatedAdminRoiRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
  AuthenticatedAdminClientesIdRoute: typeof AuthenticatedAdminClientesIdRoute
  AuthenticatedAdminClientesIndexRoute: typeof AuthenticatedAdminClientesIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAtendimentoRoute: AuthenticatedAdminAtendimentoRoute,
    AuthenticatedAdminAutomacoesLeadsRoute:
      AuthenticatedAdminAutomacoesLeadsRoute,
    AuthenticatedAdminCalendarioRoute: AuthenticatedAdminCalendarioRoute,
    AuthenticatedAdminConfigMetaRoute: AuthenticatedAdminConfigMetaRoute,
    AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
    AuthenticatedAdminDashboardClientesRoute:
      AuthenticatedAdminDashboardClientesRoute,
    AuthenticatedAdminDiagnosticosRoute: AuthenticatedAdminDiagnosticosRoute,
    AuthenticatedAdminEstrategiaRoute: AuthenticatedAdminEstrategiaRoute,
    AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
    AuthenticatedAdminMetaAdsRoute: AuthenticatedAdminMetaAdsRoute,
    AuthenticatedAdminPipelineComercialRoute:
      AuthenticatedAdminPipelineComercialRoute,
    AuthenticatedAdminRoiRoute: AuthenticatedAdminRoiRoute,
    AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
    AuthenticatedAdminClientesIdRoute: AuthenticatedAdminClientesIdRoute,
    AuthenticatedAdminClientesIndexRoute: AuthenticatedAdminClientesIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedClienteRouteRouteChildren {
  AuthenticatedClienteAtendimentoRoute: typeof AuthenticatedClienteAtendimentoRoute
  AuthenticatedClienteCalendarioRoute: typeof AuthenticatedClienteCalendarioRoute
  AuthenticatedClienteClientesRoute: typeof AuthenticatedClienteClientesRoute
  AuthenticatedClienteConexoesRoute: typeof AuthenticatedClienteConexoesRoute
  AuthenticatedClienteConteudoRoute: typeof AuthenticatedClienteConteudoRoute
  AuthenticatedClienteDashboardRoute: typeof AuthenticatedClienteDashboardRoute
  AuthenticatedClienteDiagnosticoRoute: typeof AuthenticatedClienteDiagnosticoRoute
  AuthenticatedClienteEntregasRoute: typeof AuthenticatedClienteEntregasRoute
  AuthenticatedClienteLeadsRoute: typeof AuthenticatedClienteLeadsRoute
  AuthenticatedClienteMetaAdsRoute: typeof AuthenticatedClienteMetaAdsRoute
  AuthenticatedClienteRoiRoute: typeof AuthenticatedClienteRoiRoute
}

const AuthenticatedClienteRouteRouteChildren: AuthenticatedClienteRouteRouteChildren =
  {
    AuthenticatedClienteAtendimentoRoute: AuthenticatedClienteAtendimentoRoute,
    AuthenticatedClienteCalendarioRoute: AuthenticatedClienteCalendarioRoute,
    AuthenticatedClienteClientesRoute: AuthenticatedClienteClientesRoute,
    AuthenticatedClienteConexoesRoute: AuthenticatedClienteConexoesRoute,
    AuthenticatedClienteConteudoRoute: AuthenticatedClienteConteudoRoute,
    AuthenticatedClienteDashboardRoute: AuthenticatedClienteDashboardRoute,
    AuthenticatedClienteDiagnosticoRoute: AuthenticatedClienteDiagnosticoRoute,
    AuthenticatedClienteEntregasRoute: AuthenticatedClienteEntregasRoute,
    AuthenticatedClienteLeadsRoute: AuthenticatedClienteLeadsRoute,
    AuthenticatedClienteMetaAdsRoute: AuthenticatedClienteMetaAdsRoute,
    AuthenticatedClienteRoiRoute: AuthenticatedClienteRoiRoute,
  }

const AuthenticatedClienteRouteRouteWithChildren =
  AuthenticatedClienteRouteRoute._addFileChildren(
    AuthenticatedClienteRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedClienteRouteRoute: typeof AuthenticatedClienteRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedClienteRouteRoute: AuthenticatedClienteRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  QueroSaberMaisRoute: QueroSaberMaisRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
